export const LAB_LOCATIONS = [
  'Fridge S1',
  'Fridge S2',
  'Fridge S3',
  'Fridge S4',
  'Fridge S5',
  'Fridge S6',
  'Fume Hood 1',
  'Fume Hood 2',
  'Fume Hood 3',
  'Fume Hood 4',
  'Cabinet 1',
  'Cabinet 2',
  'Cabinet 3',
  'Cabinet 4',
  'Cabinet 5',
  'Cabinet 6',
  'Cabinet 7',
  'Cabinet 8',
  'Cabinet 9',
  'Cabinet 10',
  'Cabinet 11',
  'Cabinet 12',
  'Cabinet 13',
  'Cabinet 14',
  'Cabinet 15',
  'Cabinet 16',
  'Cabinet 17',
  'Cabinet 18',
  'Cabinet 19',
  'Cabinet 20',
  'Cabinet 21',
  'Cabinet 22',
  'Cabinet 23',
  'Cabinet 24',
  'Flammable Storage 1',
  'Flammable Storage 2',
  'Lab Sink',
  'Office',
] as const

export const LAB_SUB_LOCATIONS = [
  'Shelf 1 (Top)',
  'Shelf 2',
  'Shelf 3',
  'Shelf 4',
  'Shelf 5',
  'Shelf 6 (Bottom)',
  'Top Shelf',
  'Bottom Shelf',
  'Left side',
  'Right side',
] as const
